### ISSUE TITLE
Change page with swipe

### ISSUE THREAD

**Issue by fischi87** [edward-shen/MMM-pages#10] opened 2018-08-26 08:16 UTC
Hello,

i want change the pages with a swipe but i don't know how. i don't know this about send.notification or stuff like this. i don't know where i have to write down and what i have to write down. u can help me with some examples?

thanks

**Comment by edward-shen** [comment] 2018-08-26 18:32
The `sendNotification` information is primarily meant for Magic Mirror Module developers. Unless you are developing one yourself, it really isn't useful for you. It's meant for other developers to interact with MMM-pages, for interoperablility. As a result, the issue is having other modules support MMM-pages, not the other way around.

It looks like you opened up an issue at MMM-Swipe (mochman/MMM-Swipe#10) but it looks like the author has archived the repo, which is likely because it has stopped functioning and is now unmaintained. Someone needs to fork it and 1) make it work again and 2) add in MMM-pages support. However, I'm not willing to take this on because I don't have the HC-SR04s needed to develop it. You'll likely need to ask elsewhere (maybe on the forums) to take up that module.

If you want to develop a module yourself, please refer to [the documentation](https://github.com/MichMich/MagicMirror/tree/develop/modules) for help, assuming you know JS. Otherwise, I can't do much to help you.

 If you have another maintained module that you want to work with MMM-pages, please consider creating an issue there. I'm closing this issue because it is unfortunately not something I can solve, as it doesn't relate to MMM-pages.

**Closed by edward-shen** 2018-08-26 18:32 UTC
