### ISSUE TITLE
How do i actually change pages

### ISSUE THREAD

**Issue by Kevsw99** [edward-shen/MMM-pages#14] opened 2018-10-25 05:06 UTC
Hi edward, i am currently doing this magic mirror modules as a project for my internship, however i am currently stuck at creating pages and i would also like to make new pages for more modules to appear. PS, i am quite bad a programming thus when i read the page indicator modules, i cant really understand how do i configure it into the js file, below is my config.js coding

```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
        address: "localhost", // Address to listen on, can be:
                              // - "localhost", "127.0.0.1", "::1" to listen
on loopback interface
                              // - another specific IPv4/6 to listen on a
specific interface
                              // - "", "0.0.0.0", "::" to listen on any interface
                              // Default, when address config is left out, is
"localhost"
        port: 8080,
        ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to
allow all IP addresses
                                                               // or add a
specific IPv4 of 192.168.1.5 :
                                                               //
["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
                                                               // or IPv4
range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
                                                               //
["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

        language: "en",
        timeFormat: 24,
        units: "metric",

        modules: [


{
    module: 'MMM-LICE',
    position: 'bottom_right',                 // Best in left, center,
or right regions
    config: {
                accessKey: "xxxxx", // Free account & API
Access Key at currencylayer.com
                source: "USD",                    // USD unless you upgrade from free account
                symbols: "AUD,CHF,EUR,GBP",       // Currency symbols
                useHeader: false,
                header: "Money Exchange",
                maxWidth: "300px",
    }
},
{
    module: 'MMM-OnScreenMenu',
    position: 'bottom_left',
    config: {
        touchMode: true,
        menuItems: {
        monitorOff: { title: "Turn Off Monitor", icon: "television",
source: "SERVER" },
        restart: { title: "Restart MagicMirror", icon: "recycle",
source: "ALL" },
        refresh: { title: "Refresh MagicMirror", icon: "refresh",
source: "LOCAL" },
        moduleHide1: { title: "Hide Clock", icon: "minus-square", name: "clock" },
        moduleShow1: { title: "Show Clock", icon: "plus-square", name: "clock" },
        reboot: { title: "Reboot", icon: "spinner", source: "ALL" },
        shutdown: { title: "Shutdown", icon: "power-off", source: "ALL" },
        },
        enableKeyboard: true,
    }
},




        {
                        module: "alert",
                },
                {
                        module: "updatenotification",
                        position: "top_bar"
                },
                {
                        module: "clock",
                        position: "top_left"
                },
                {
                        module: "calendar",
                        header: "US Holidays",
                        position: "top_left",
                        config: {
                                calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
                                        }
                                ]
                        }
                },
                {
                        module: "compliments",
                        position: "lower_third"
                },
                {
                        module: "currentweather",
                        position: "top_right",
                        config: {
                                location: "Republic of Singapore",
                                locationID: "1880251",  //ID from
http://bulk.openweathermap.org/sample/; unzip the gz file and find
your city
                                appid: "xxxxx"
                        }
                },

                {
                        module: "newsfeed",
                        position: "bottom_bar",
                        config: {
                                feeds: [
                                        {
                                                title: "New York Times",
                                                url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
                                        }
                                ],
                                showSourceTitle: true,
                                showPublishDate: true
                        }
                },

                {
                      module: 'MMM-pages',
                      config:
                        {
                        modules:
                        [["weatherforecast", "newsfeed", "MMM-LICE"]
                        ["calendar", "compliments"]],
                        excludes:["MMM-OnScreenMenu", "clock", "currentweather",
"MMM-page-indicator"],

                        }

                       },
                       {
                        module: 'MMM-page-indicator',
                        position: 'bottom_bar',
                        config:{
                        pages: 2,
                        }

                        },

        ]



};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**Comment by edward-shen** [comment] 2018-10-25 14:39
I have delete your API keys from the post and the edit history. It is good practice to keep your API private, as they are unique secret keys for your purposes only.

MMM-Pages does not have any way to change pages by itself. This is by design, as there are a dozen different ways to interface with a magic mirror, so it's better for users to select their own module to interface with the mirror. MMM-page-indicator does provide some form of page selection by clicking on the circles, but that is more or less a last-resort and I'd advise against it for normal usages, unless you have a touch screen.

As for your config, you have a typo:
```
[["weatherforecast", "newsfeed", "MMM-LICE"]
["calender", "compliments"]],
```

Should be 
```
[["weatherforecast", "newsfeed", "MMM-LICE"],
["calendar", "compliments"]],
```

To add a new page, one simply needs to add their module as another array:
```
[["weatherforecast", "newsfeed", "MMM-LICE"],
["calendar", "compliments"],
["page3module1", "page3module2"]],
```

This can be repeated for as many pages you want.

You also don't need to specify the number of pages in MMM-page-indicator. Configuration for MMM-page-indicator is done automatically from MMM-pages.

**Comment by Kevsw99** [comment] 2018-10-29 00:10
Alrite thank you so much, ill try it out later and get back to you on whether it can be done.

**Comment by Kevsw99** [comment] 2018-10-30 04:11
Hey Edward, i did tried the code and it does work, but i do have a question.  For Example;

[["weatherforecast", "newsfeed", "MMM-LICE"],
["calendar", "compliments"],
["page3module1", "page3module2"]],

Do i do this kind of arrays for my other modules like for example football news to be shown on like page 2 or 3 , like do i just need to add in another array which specifies where this modules should be just like array above, thank you so much for your help so far and i hope you can help me clarify my doubts again.

**Comment by Kevsw99** [comment] 2018-10-30 04:37
Alrite i will work on that, and 1 more question, for example, i wanna add a modules 3 on the same position but different pages, so i do just need to specify the code in the config js file something this right;

                {
                        module: "calendar",
                        header: "US Holidays",
                        position: "top_left",
                        config: {
                                calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
                                        }
                                ]
                        }
                },
 then  example module: "footballNews",
                        header: "ball",
                        position: "top_left",

finally;
[["calendar"],
["footballNews"],
["page1module1", "page2module1"]],

i assume its something like this right?

**Comment by edward-shen** [comment] 2018-10-30 04:47
Yep!
You tell where the modules to be in their own configurations, and MMM-pages just tells them when to show up together!

**Comment by Kevsw99** [comment] 2018-10-30 05:16
Ah thats why it doesnt work on one page, so do i ignore the excluding part if i do want to add them into the second page;

excludes:["MMM-OnScreenMenu", "clock", "currentweather","MMM-page-indicator"],

**Comment by edward-shen** [comment] 2018-10-30 15:55
If you want to add `clock` to a specific page rather than showing up all the time, you'll need to remove it from `excludes` and then add it to the page you want. Any module in `excludes` will show up on all pages.

**Comment by Kevsw99** [comment] 2018-10-31 04:46
Oh wow, words cannot describe how grateful i am Edward, thank you for all your help so far, and ill do my best in adding more modules and i will also like to try adding an auto page changing module if possible, once again, thank you so very much 👍

**Comment by edward-shen** [comment] 2018-10-31 20:52
Take a look at the `rotationTime` config option.

**Comment by Kevsw99** [comment] 2018-11-01 03:33
I don't know if i am blind but i can't seem to find it....

**Comment by edward-shen** [comment] 2018-11-01 14:59
It's under the configuration options header on the main page of the repo.

**Comment by Kevsw99** [comment] 2018-11-02 04:11
OMG im such a blur fool, thank you so much for your help edward, you are the best 👍

**Comment by edward-shen** [comment] 2018-11-02 16:59
Glad to be of help. Closing.

**Closed by edward-shen** 2018-11-02 16:59 UTC

**Comment by cowboysdude** [comment] 2018-11-22 15:29
I'm going to piggy back off of this closed issue because I'm having a similar issue....  Here's my config:
When I try to go to the second page it does nothing at all.   Suggestions?   

I'm running this on a 32" touch screen using a mini itx computer running Unbuntu 18...  Thank you!

              {
			   disabled: f,
		module: 'MMM-Cursor'		 
	      },
             {
	    disabled: f,
            module: 'MMM-pages',
              config: {
                modules:
                    [[ "MMM-NOAA3", "MMM-Astrology"],
                     [ "MMM-ESPN" ]],
                excludes: ["MMM-Glock", "MMM-page-indicator"],
               }
             },
             {
		disabled: f,
        module: 'MMM-page-indicator',
        position: "bottom_bar"
          },

**Comment by cowboysdude** [comment] 2018-11-22 16:29
Oh I just used shorthand ...what you don't see at the top of my config is:

var t = true;
var f = falise;

So instead of using 'disabled: true'  or 'disabled: false' I just use t or
f :)

That sounds like a great idea!!  Going to get my feelings hurt, they're all
my modules LOL  NO worries.....I didn't try it on rotating and that
worked.....

**Comment by cowboysdude** [comment] 2018-11-22 16:37
I disabled all the modules except the stock calendar module and still cannot get the pages to rotate on clicking the indicator......

**Comment by cowboysdude** [comment] 2018-11-22 16:49
Okay so I figured it out......  I remember I had this problem once so I added this to my custom.css file and it fixes the issue:

     .fullscreen.above {
      z-index: -1;
      }

**Comment by edward-shen** [comment] 2018-11-22 16:51
I thought I recognized your username!

Is that a css fix that is specific to your issue or something that should be implemented in MMM-pages? I don't have access to a magic mirror right now so I'm not familiar with that selector.

**Comment by cowboysdude** [comment] 2018-11-22 17:02
I moved it from my custom.css file to the MMM-pages css file and it works.  It wouldn't to do that :)  I'll do a PR ;)

**Comment by HayunaLi** [comment] 2022-06-05 03:51
Hello Edward,

I am using an IR frame and MMM-pages and MMM-page-indicator by you.
I can't seem to click on the page indicator dots with the IR frame.
I am using MMM-touch library which does not appear in the magic mirror 3rd library, you would have to google it. 

But I do not know how to send the right notification to page indicator so that it responds to the IR frame.

I know this is probably very simple for you, but are you able to help me?

**Comment by edward-shen** [comment] 2022-06-05 04:24
Hi @HayunaLi, please do not necro old issues, you've just notified 2 other people from 2018. Additionally, I do not offer support for other modules, so you will need to ask for support on the forums instead.
